### ISSUE TITLE
Issue with public bucket

### ISSUE THREAD

**Issue by vedantbajaj96** [Esri/OptimizeRasters#111]
OR fails to convert data which sits in public buckets (AWS) which restrict region information

**Comment by Chamlika** [comment]
@vedantbajaj96 @abhiataero @CrisCD 

Unable to recreate with the latest on GitHub. Please upgrade and try.
You may get a warning message like (log-warning:get/bucket/region (Unable to locate credentials), due to restricted AWS bucket permissions that OR may required to work with, but it isn't critical and you should be able to continue.
