### ISSUE TITLE
LERC support in ArcGIS Image Server 10.8.1 (Linux)

### ISSUE THREAD

**Issue by elwoodhouse** [Esri/OptimizeRasters#119]
This is probably not directly related to OptimizeRasters but thought I would post in case someone can give me a quick answer.

I am creating MRFs through the Imagery_to_MRF_LERC.xml template with the MRFs uploaded to S3, then adding them to a mosaic dataset and publishing the mosaic dataset to Image Server on Linux.

When I add the image service to ArcGIS Pro 2.6, the rasters do not draw. When I try to use the Image Server Rest API export image command, I can't get an image to be returned. 

Through troubleshooting, I've found that if I add the same mosaic dataset to Pro locally, the rasters are able to be drawn, so I don't think it's an issue with access to S3 or the rasters. If I publish the image service with rasters using the Imagery_to_MRF_JPEG.xml template, the service draws fine in ArcGIS Pro from image server.

Is there something that I need to configure to get LERC rasters to be served through ArcGIS Image Server?

**Comment by lucianpls** [comment]
@elwoodhouse 
If you are using raster proxies in the mosaic, make sure that the Linux user that runs arcgis server (arcserver if I recall) has write access to the cache folder. If the cache files/folders can't be created, it will act as you describe.

**Comment by elwoodhouse** [comment]
Thanks for the response, I am using proxy files. My understanding of the cache directory is that it's created on the client side. ArcGIS Pro and accessing the rest api is happening from a windows workstation. When I use JPEG compression the cache files are created successfully in the cache directory, when I use LERC compression no files are created (using the same cache settings as the JPEG compression rasters). This would suggest that it isn't a cache setting, but happy to troubleshoot if I've misunderstood something.

**Comment by lucianpls** [comment]
@elwoodhouse 
The cache gets created where the proxy gets used. It has nothing to do with the final "client". The proxy string is in the mosaic. In this case, the server uses the mosaic, thus the proxies, so the cache folder used is on the server.
When you open the mosaic directly with ArcPro (not via the server), it's ArcPro who uses the proxy, so the cache gets created on the ArcPro machine. It's the same exact mechanism in a different context.
So yes, you do have to make sure that the server user (arcserver) can create the files AND that it can access to the source S3 bucket through whatever mechanism you set up the proxies to use. In addition, the cache folder has to be local to the server machine, it can't be on a networked share. Otherwise you will get corrupt data, even if a single machine writes to that folder.

The caching/cloning works the same way regardless of the compression, you should see the files getting created and growing on the server. If not, the server has an access problem.

**Comment by lucianpls** [comment]
@elwoodhouse 
Ah, OK, now that I read the original message more careful, it looks like we were talking past each other.
Everything I said is correct, but it sounds like you have it working (with or without the sever cache) when using JPEG but not when using LERC.

If that is the case, it could be indeed a LERC version issue. If the OptimizeRasters is using a newer LERC implementation than the server and Pro, then the converted files might not work.  It can happen only if the rasters have multiple bands and the template is using pixel interleaved. Post the content of one of the .mrf files.

And you should still make sure that the server can create the cache, for either LERC and JPEG. Otherwise, even if the server seems to work, the sever cache won't exist so it will be slow, accessing S3 for each and every request.

**Comment by lucianpls** [comment]
@elwoodhouse 
You can try setting the V1:1 in the custom MRF options in the OR template. That will force the original version of LERC, which is the most compatible.

**Comment by elwoodhouse** [comment]
Thanks for the pointers, much appreciated. I'll get the server side cache dir working and try the V1:1 flag. This is the MRF content:
<MRF_META>
  <Raster>
    <Size x="19036" y="23536" c="1" />
    <PageSize x="512" y="512" c="1" />
    <Compression>LERC</Compression>
    <DataValues NoData="0" />
  </Raster>
  <GeoTags>
    <BoundingBox minx="459240.00000000" miny="7852540.00000000" maxx="485890.40000000" maxy="7885490.40000000" />
    <Projection>PROJCS["WGS_1984_UTM_Zone_55S",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",147],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",10000000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","32755"]]</Projection>
  </GeoTags>
  <Options>V2=ON</Options>
  <Rsets model="uniform" scale="2" />
</MRF_META>

**Comment by lucianpls** [comment]
Yes, that is V2, but it is single band, which forces an old version of LERC V2 which is compatible with all ArcGIS versions that support raster proxies.  So we're back to the cache or the S3 access.

**Comment by lucianpls** [comment]
Can you open that MRF with ArcPro, local?

**Comment by elwoodhouse** [comment]
Yep, through an acs connection (proxy raster uses /vsis3 though):
![image](https://user-images.githubusercontent.com/38488541/115348897-8cbaa100-a1f6-11eb-9f9b-b4f0bef610b0.png)

**Comment by abhiataero** [comment]
@elwoodhouse have you set any cloud store on the server, just make sure the permission are set correctly 

- The ACS file is copied on the Linux server and ArcGIS account has the required permission
- 

other test you can do it is to check at gdal level if there is access 

use the below python in wine environment 
"c:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\python.exe" 

gdal.Translate('outputdata', inputdata)

**Comment by lucianpls** [comment]
It's certainly not in LERC then. It has to be the server, either lacking access to S3 or being unable to use the cache folder, in that order.

**Comment by elwoodhouse** [comment]
Got the cache directory working and the image is now drawing! Thanks for the diagnosis and explanation of how the raster proxies work, it's much appreciated. The performance does seem to be better with the cache directory.

**Comment by lucianpls** [comment]
@elwoodhouse 
Great, glad to be able to help!

**Comment by elwoodhouse** [comment]
Image server didn't have access to a proxy cache directory.
