### ISSUE TITLE
Hardcoded use of S3 Virtual addressing/hosting

### ISSUE THREAD

**Issue by mbeaucha** [Esri/OptimizeRasters#135]
Lines 337 and 3285 of OptimizeRasters.py hardcode the use of virtual addressing for S3. This breaks compatibility with certain regions and/or third-party S3 API implementations like MinIO. The code should be updated to either respect the value of 'addressing_style' in the ~/.aws/config file or the value of AWS_VIRTUAL_HOSTING, which is used by the embedded GDAL package to configure the same setting, or both. For completeness this should be a setting in the OptimizeRasters.xml file as well and an optional command line argument.

**Comment by abhiataero** [comment]
@mbeaucha  optimize raster support the addressing style from /.aws/config so in that case it should just work. in the template files we refer it using the profile. The profile is defined in the .aws/config

**Comment by Chamlika** [comment]
@mbeaucha Hi, the addressing style was forced into 'virtual style' because the 'path style' type is not longer recommended by AWS and could be soon made obsolete if not already for the older clients.  https://github.com/Esri/OptimizeRasters/issues/97#issuecomment-881205958. However, we'll look forward to take your recommendation to derived the path style using the ENV/config if set, else default to 'virtual' if omitted. Thanks!

**Comment by abhiataero** [comment]
@Chamlika  has this been taken care of

**Comment by Chamlika** [comment]
> @Chamlika  has this been taken care of 

@abhiataero Will look forward to include in the next release.

**Comment by Chamlika** [comment]
@mbeaucha Let us know if the fix works for you, thanks!
